name: Build - Windows - RealOTX 7.72

on:
  workflow_dispatch:

jobs:
  build:
    name: Windows Release x64
    runs-on: windows-2022

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install 7zip
        run: choco install 7zip -y

      - name: Download OTX Windows SDK
        run: |
          curl -L "https://github.com/mattyx14/otxserver/raw/otxserv2/sources/otx-windows-sdk.7z" -o sdk.7z
          7z x sdk.7z -oC:\otx-sdk
          echo "TFSSDKDir=C:\otx-sdk\otx-windows-sdk" >> $env:GITHUB_ENV

      - name: Install Boost
        run: |
          choco install boost-msvc-14.2 --version=1.84.0 -y
          echo "BOOST_ROOT=C:\local\boost_1_84_0" >> $env:GITHUB_ENV

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Build solution
        run: |
          msbuild sources/msvc/TheOTXServer.sln /p:Configuration=Release /p:Platform=x64 /m

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: realotx-7.72-windows-x64
          path: sources/msvc/x64/Release/
